### ISSUE TITLE
Update php doc blocks

### ISSUE THREAD

**Issue by rramo012** [BoldGrid/prime#30]
Update all PHP files within prime to use crio define package and license type during a build command

**Comment by timelsass** [comment]
This regex was rewriting files in really weird ways.  I'm not sure why, but I couldn't get it to work properly.  In the end I just ended up having a simple find replace for @package Prime in the php files.  I think this resolves the underlying issue for the build process for now, but in the future we can explore changing license types and automatically adding them to headers when they aren't present.  It would be a nice addition, but not an issue related to just updating the docblocks for the time being.  This has all been handled in v2.2.0 replace, so I will close this issue out.
