### ISSUE TITLE
Remove x displays as /

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/prime#36]
WooCommerce uses 'x' for product quantities and as a remove symbol. In Firefox and Chrome the 'x' displays as '/' for some reason.
![woocommerce-x-display](https://user-images.githubusercontent.com/20601160/50642239-8bd3a780-0f38-11e9-974a-5e462ae31443.PNG)

**Comment by timelsass** [comment]
this is up to a designer to change, or a user to change as they see fit.  The screenshot displayed shows a theme using "Exo 2":  https://fonts.google.com/specimen/Exo+2 

If that's not the font a user likes, they can easily change it in the customizer.
