### ISSUE TITLE
Rename Crio menu item

### ISSUE THREAD

**Issue by timelsass** [BoldGrid/prime#40]
Currently the crio menu item is called "Crio" under the appearances nav_menu.  This should be updated to "Crio Dashboard," or "Crio Settings."  This will help make it stand out a bit in the admin menu, and give users a reason to actually click on it.  Just the name Crio is hard to overlook by itself, and doesn't really indicate what happens when you click on it.

**Comment by nicolepaschen** [comment]
Closed - added new Crio Pro page in latest release
