### ISSUE TITLE
Terms and Conditions display at Checkout

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/prime#41]
This displays very strangely with the text wrapping even though there’s room on 1 line for all of it. Also the checkbox should probably be left aligned.
![terms-conditions-checkout](https://user-images.githubusercontent.com/20601160/50643773-fa1a6900-0f3c-11e9-9e68-373dac89ed78.PNG)

**Comment by timelsass** [comment]
Unable to replicate this, but there have been two WooCommerce bug sweeps on v2 of Prime and framework since this ticket was created, perhaps the template has been removed or the issue was resolved through alternative fixes.
