### ISSUE TITLE
Jetpack fatal on switch theme from Crio

### ISSUE THREAD

**Issue by cssjoe** [BoldGrid/prime#52]
**Describe the bug**
Every time I switch my theme from Crio 2.2.5 to any other theme, Jetpack 7.7 hits a PHP fatal error.

**To Reproduce**
1. Go to Appearance >> Themes.
2. Activate Crio.
3. Activate any other theme, such as twentynineteen.
4. See error:

>The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.
>Fatal error: Uncaught Exception: Serialization of 'Closure' is not allowed in /home/user/public_html/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/Queue.php:33
>Stack trace:
>#0 /home/user/public_html/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/Queue.php(33): serialize(Array)
>#1 /home/user/public_html/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/Listener.php(241): Automattic\Jetpack\Sync\Queue->add(Array)
>#2 /home/user/public_html/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/Listener.php(116): Automattic\Jetpack\Sync\Listener->enqueue_action('jetpack_sync_cu...', Array, Object(Automattic\Jetpack\Sync\Queue))
>#3 /home/user/public_html/wp-includes/class-wp-hook.php(286): Automattic\Jetpack\Sync\Listener->action_handler(Array, Array)
>#4 /home/user/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
>#5 /home/user/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
>#6 /home/user/public_html/wp-content/plugins/jetpack/ in /home/user/public_html/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/Queue.php on line 33

**Expected behavior**
The theme should switch without error.

**Comment by nicolepaschen** [comment]
I can switch between Crio and 2020 theme without issue with Jetpack active. Closing.
