### ISSUE TITLE
[Bug] Social Media menu items are reset when switching between V1 themes.

### ISSUE THREAD

**Issue by joe9663** [BoldGrid/prime#78]
**Describe the bug**
If you add a custom menu item to your social media menu and then switch to a different V1 theme, the custom link is removed from the menu.

**To Reproduce**
1. Install an Inspiration with the default social media menu items (Facebook, Twitter)
2. Add a custom link to social media menu for Instagram
3. Change to a different V1 theme
4. The Instagram link is removed from the menu once the new theme is activated.

**Expected behavior**
Menu data should persist across theme switches and should not revert to the default settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/17650704/84416250-f420c100-abe1-11ea-9ab4-01f6a1aa5fd4.png)
![image](https://user-images.githubusercontent.com/17650704/84416410-2c280400-abe2-11ea-9dda-5a3d2c71f24c.png)

**Comment by nicolepaschen** [comment]
Inspirations doesn't let you change between v1 themes anymore, closing
